import { iconFor } from './file-types.js'

/**
 * Convert a scanned tree into a VitePress sidebar. We prepend a small
 * emoji icon to non-MD entries so the user can tell at a glance what
 * type of asset each entry is.
 */
function treeToSidebar(nodes) {
  const out = []
  for (const node of nodes) {
    if (node.type === 'file') {
      // index files become the folder's link, not a separate sidebar entry
      if (node.isIndex) continue
      out.push({
        text: iconFor({ kind: node.kind, viewer: node.viewer }) + node.title,
        link: node.link,
      })
      continue
    }
    const item = {
      text: node.title,
      collapsed: false,
      items: treeToSidebar(node.children),
    }
    if (node.indexLink) item.link = node.indexLink
    out.push(item)
  }
  return out
}

/**
 * Build the serializable part of the VitePress UserConfig.
 *
 * `srcDir` is the absolute path of the mirrored content directory
 * (<runtime>/content/), NOT the user's original ./docs path. The mirror
 * step has already populated it with symlinks + stubs.
 */
export function buildVitePressConfig({ srcDir, tree, title = 'Docs' }) {
  const sidebar = treeToSidebar(tree.children)
  return {
    title,
    srcDir,
    cleanUrls: true,
    lastUpdated: true,
    // Lenient: docs in the wild contain broken links. Don't fail build over them.
    ignoreDeadLinks: true,
    // Skip files/folders whose name starts with '_' or '.'.
    // Mirrors scan.js's ignore rules so VitePress doesn't serve hidden content.
    srcExclude: ['**/_*', '**/_*/**', '**/.*', '**/.*/**'],
    themeConfig: {
      sidebar,
      outline: { level: [2, 3] },
      search: { provider: 'local' },
    },
    mermaid: {
      // sensible defaults; user can override via their own root config later
      theme: 'default',
      // Don't inject mermaid's "Syntax error" SVG into the DOM when a diagram fails to parse — that
      // error element isn't cleaned up on VitePress SPA navigation, so it lingers at the bottom of
      // every page visited afterwards (even pages with no diagrams). A bad diagram just won't render.
      suppressErrorRendering: true,
    },
    vite: {
      resolve: {
        // critical: keep symlink paths so module resolution stays inside the
        // runtime tree (and finds our node_modules symlink).
        preserveSymlinks: true,
      },
    },
  }
}

/**
 * Serialize the config into a runnable ESM module string.
 *
 * `withMermaid()` injects markdown-it-mermaid handling so ```mermaid blocks
 * in any .md file (and our generated .mmd stubs) render as diagrams.
 */
export function serializeConfig(config) {
  return `// auto-generated by docs-view — do not edit
import { withMermaid } from 'vitepress-plugin-mermaid'

export default withMermaid(${JSON.stringify(config, null, 2)})
`
}
