*** Settings ***
Resource    ../../KeywordLibraries/YourProject/VerificationKeywords/VerificationKeywords_Login.resource
Resource    ../../KeywordLibraries/YourProject/HighLevelKeywords/HighLevelKeywords_Login.resource
Resource    ../../KeywordLibraries/YourProject/HighLevelKeywords/HighLevelKeywords_QuanLyNhanVien.resource
Resource    ../../KeywordLibraries/YourProject/VerificationKeywords/VerificationKeywords_QuanLyNhanVien.resource
Resource    ../../KeywordLibraries/YourProject/LowLevelKeywords/UI_Utils.resource
Resource    ../../KeywordLibraries/YourProject/HighLevelKeywords/HighLevelKeywords_Menu.resource